### ISSUE TITLE
Running CAM-FV on Cori at NERSC: "Cannot open file 'cam_init_files' for read"

### ISSUE THREAD

**Issue by jasonltorchinsky** [NCAR/DART#130]
Hello,

I am currently trying to run `cam-fv` in the `models` subdirectory, following the general procedure of the `lorenz_63` example. In particular, these are the steps I have performed to try to run `cam-fv`:

1. Used `git clone` to obtain the latest release of DART, in particular I have cloned it into a directory called `DART`.
2. Downloaded the `Manhattan_large_files.tar.gz` file and unzipped it in my `DART` directory.
3. (Cori-specific) I have purged all modules, and loaded the modules `prgEnv-gnu/6.0.5`, `openmpi/4.0.2`, and `cray-netcdf/4.6.3.2`.
4. Navigated to the `work` subdirectory of the `cam-fv` directory, and issued the command `./quickbuild.sh -mpi`. This appears to build the program without issue.
5. Submitted the following batch script:
```
  1 #!/bin/bash
  2
  3 #SBATCH --time=0-00:20:00
  4 #SBATCH --job-name=cam-fv
  5 #SBATCH --output=%x.out
  6 #SBATCH --error=%x.err
  7
  8 #SBATCH --qos=debug
  9 #SBATCH --nodes=1
 10 #SBATCH --tasks-per-node=64
 11 #SBATCH --constraint=knl
 12
 13 #SBATCH --account=m3698
 14 #SBATCH --mail-user=********
 15 #SBATCH --mail-type=all
 16
 17 cd $SLURM_SUBMIT_DIR
 18 module purge
 19 module load PrgEnv-gnu
 20 module load openmpi/4.0.2
 21 module load cray-netcdf/4.6.3.2
 22
 23 mpirun -np 64 ./perfect_model_obs
 24 mpirun -np 64 ./filter
```
The submitted job fails, and I've attached the error and output files
[cam-fv.err.txt](https://github.com/NCAR/DART/files/5822411/cam-fv.err.txt)
[cam-fv.out.txt](https://github.com/NCAR/DART/files/5822413/cam-fv.out.txt)

In particular, the output file `cam-fv.out` states that the file "`cam_init_files`" cannot be opened, which does not appear to be a file in the DART repository nor the `Manhattan_large_files.tar.gz` file. I think the issue is that there are some other commands I should be running in the batch script, but I am not sure what those are. Any help would be greatly appreciated.

Cheers,

Jason

**Comment by kdraeder** [comment]
Hi Jason,
thanks for working with DART!
Cam-fv requires a setup step that's not necessary for lorenz_63,
since it's a large model, and the data assimilation cycling is actually
controlled by the CESM (CAM-FV) scripts, instead of by DART.
Go to .../cam-fv/shell_scripts/cesm2_1 and work your way through
the setup_hybrid script.  You'll need to have access to a CESM
package.  If you're not familiar with CESM, you'll need to spend 
some time with it and its documentation.
After you successfully run setup_hybrid,
there will be a "CASE" directory, where you will go to run the job.
We're working on updating the documentation to all of this,
but most of what you need to know is in the setup_hybrid script.
Kevin
