### ISSUE TITLE
even_sphere workflow script

### ISSUE THREAD

**Issue by kdraeder** [NCAR/DART#206]
Date: 2021-4-26

### Overview:
I'm starting from even_sphere.m and working to generate a series of obs_seq.in files.
It took some work to figure out the series of steps required to do that,
using programs compiled in the cam-fv context.  A choice of model
is required because the create_\*seq\* programs *can* create identity obs, 
so they *must* call *a* model's static_init_model, regardless of whether identity obs 
are actually requested.  Cam-fv's static_init_model requires 2 input files,
which seems more cumbersome than necessary for this task.

I'm part way to combining all of these steps into a script,
which is an expanded version of even_sphere/run_fixed_network_seq.csh,
and I'd like opinions about whether a similar (simpler? more generic?) script
would be useful in DART, or whether we should focus on keeping the usage pattern
more modular or granular; running one small script or program at a time.

### Terminology:
**even_sphere.m** Matlab script to generate a text file for use by create_obs_sequence.
It generates a nearly uniform distribution of obs profiles on a sphere, at specified levels.  
The obs are nominally 
RADIOSONDE_{TEMPERATURE,U_WIND_COMPONENT,V_WIND_COMPONENT}
**cam-fv** The model I chose (by default) to be the context in which the obs programs were built.  

### Functional Specification:
Streamline the process (at least in the cam-fv context) of generating 
a sequence of synthetic obs files from a text file of locations.
This would make the sequence simpler to create and keep the process organized.
It also would help encode some conventions about naming and storing obs_seq files.

### Technical Specification:
Combine setup for, and calls to, create_obs_sequences and create_fixed_network_seq
into a driver script.

### Open Issues:

*  I could be unaware of existing scripts (except run_fixed_network_seq.csh) 
   that already do this.
*  This may not be useful enough to commit to DART.
*  The current goal is very application specific; it may need to be more general.
*  Include running even_sphere.m into the script.  (Can Matlab be run that way?)

### Nongoals
*  Updgrading create_obs_sequence and create_fixed_network_seq (and ...?) to only call static_init_mod when identify obs will be requested.

**Comment by nancycollins** [comment]
i'm in agreement with your non-goal because those programs can't predict whether the input is going to include identity obs  or not - they can appear at any time - so the program has to call static_init_model() at the start in all cases.

normally programs like this are compiled in the work directory of a particular model, so there's a mkmf_xxx and path_names_xxx  file to build the executable, and then it's run there so any necessary files are typically already there.   so if you are making a script you might want to include it (if there's agreement it's useful) in the cam-fv/scripts dir, not in the observations/obs_converters/even_sphere dir.   or you can make a script there but have the instructions include copying the script to a particular model's work directory before running it.

**Comment by kdraeder** [comment]
Storing the script in cam-fv/scripts would make more sense.
I was following the precedent I found; even_sphere directory/run_fixed_network_seq.csh.
But maybe that should be removed, or moved to the models/... where it belongs.

I agree that it makes sense to run the create_* programs where they are built, for small obs_seq files.
But for long series of larger files, it can be more convenient to run them in a different directory,
such as /glade/p/cisl/dares/Observations.  Maybe there should be a section in the create_* program
rst files suggesting using a script, if it exists, from the model's scripts directory, if big files will be made.

It's out of the scope of this issue, but I was imagining that there would be a user supplied argument
saying "I won't request any identity obs", which would enable the programs to skip the static_init_model.
I haven't looked into them deeply to see if that's reasonable.

**Comment by nancycollins** [comment]
kevin, i just thought about this some more.

i don't think identity obs and the even_sphere generator have anything to do with each other.   that matlab script generates evenly spaced points around a sphere at fixed lat/lons.  identity obs are at their own pre-determined locations.  you don't have to prevent these executables from generating identity obs; the inputs generated by this tool won't ask for them.  

in this case we often include models/template/model_mod.f90 in the path_names file which satisfies the required subroutines but are never called.  it has no dependencies.  i believe the path_names file in the observations/utilities/threed_sphere dir uses that so it's model agnostic.   

where are you compiling the executables used for this process? (create_obs_sequence in particuar.)   if in the cam work dir, then you need to run it someplace where any of the executables compiled for cam will run.  if someplace else, what model_mod.f90 you used to build the executables matters.

**Comment by kdraeder** [comment]
Yes, I just grabbed the create_obs_sequence which I'd already made in cam-fv/work.
I didn't realize at the time that it has dependencies in it.  Making a new create_ without dependencies
is a better choice, but it's not the natural choice for someone coming at this from the models
realm of DART.  That's another suggestion that would be useful to describe in the rst files.

**Comment by nancycollins** [comment]
i think you're exactly right about needing more info in .rst files.  for any use, all executables compiled in a model's work directory depend on anything that the model_mod needs - init files, etc.  i don't think we say that anywhere.  that's not specific to this converter so documenting it only here probably isn't sufficient.   

for this converter, maybe documenting there are two options is helpful.   users can compile a version of create_obs_seq and create_fixed_network_seq with the template model_mod to make them completely portable.  but all models already have make files for these two utilities, so they're already built if someone has compiled their executables already.  using the ones they already have might be easier.  we should document somewhere that any executable built in a work directory with a specific model_mod will require whatever aux files are needed - that applies to more than just these two obs tools.  and of course, any dart executable will require an input.nml in the current directory.  (that's normally the case, but it does make it harder to write generic utility programs that you might call from any directory including those w/o an input.nml.)

you probably ran into this because this converter, unlike some of the others, isn't a single self-contained executable program but depends on the standard obs programs that we generally compile in the model work dir.   all models have mkmf's to make a create_obs_sequence and create_fixed_network_seq because they're both used in our tutorials and they're a way we recommend people make test obs easily.  

i think having more info in the .rst file for this converter, and maybe more docs where ever the model_mod.f90 file is documented (about dependencies) might help the next person.  if you think your script for cam-fv would be useful for others, i'd put it in the cam-fv scripts dir but i wouldn't worry about trying to make a universal one.  there are just too many variables for that to be feasible, i think.  (e.g. for the bgrid model, which we've used this with before, the vertical has to be model levels, not pressure, and can only be 1 or 2.  so the matlab has to be customized anyway before use depending on what goal you have in mind.)

**Comment by kdraeder** [comment]
I think that we're reaching a consensus, so here's a draft plan, which @hkershaw-brown can join in guiding.

Move the script I've developed to cam-fv/scripts.
Generalize it slightly to 
*  handle additional text files (beyond even_sphere files),
*  be runnable as a batch job (for larger files andor sequences),
*  follow more script code conventions.

? Remove the existing run_fixed_network_seq.csh script from obs_converters/even_sphere.
Put it in models/template/scripts?

Update documentation:
**obs_converters/even_sphere**;
*  Add instructions (or pointers to them) in README.rst (or readme.rst?) 
   about building and running the create_* programs; choosing a models/...
*  and the potential availability of scripts in models/.../scripts for using 
   the output of even_sphere.m

**assimilation_code/programs/readme.rst**
**obs_converters/README.rst**? 
**models/README.rst**?
**...?**
*  Include more instructions about building the code in models/.../work directories
   and the possible dependencies that could create.
*  Identity obs could require non-default input files to static_init_model 
   in order to get the right grid.

**Comment by nancycollins** [comment]
adding your script to the cam-fv/scripts dir sounds fine.  

i don't think you want to remove the original script from the even_sphere directory - it is pretty specific to just that converter.  it might need more comments/help with use.  most other converters are formed by making an executable program that doesn't need a script.  also, i don't think this particular converter is used much, to be honest, and doesn't merit adding it to a general models templates directory.  it's making synthetic obs, while most experiments are using converters to make real obs.

in your last section above, i wouldn't mention identity obs and static_init_model.  that's just one example of a routine that uses get_state_meta_data() and might make it seem like it's the only one - which isn't true.  any program that is compiled with a model_mod will have it's static_init_model routine called, so any executable built in the work directory will have dependencies.  your first bullet covers the second in that last section.  for example, many static_init_model() routines need to read in a grid, land surface types, surface elevation, etc - all kinds of aux data.  some might be read in from a single template model restart file (in which case the user needs to know that the template file needs to match their other ensemble member files) and any other aux files need to be consistent with the run they're going to do.  programs like get_closest_member() will also call the get_state_meta_data() routine from the model_mod, so there's nothing special about identity obs calling that routine as well.  it happens in multiple places in the system, in addition to its use by filter.

your other plans for adding more to docs sound good.
