### ISSUE TITLE
quad_utils_mod vs cam-fv model quad_vals

### ISSUE THREAD

**Issue by hkershaw-brown** [NCAR/DART#249]
See pull https://github.com/NCAR/DART/pull/247 for the original discussion on this. 

quad_utils_mod.f90 uses `invals(4, nitems)`
cam-fv/model_mod.f90 uses `quad_vals(ens_size,4)` !< array of interpolated values

gitm is the other model that uses quad_vals

**Comment by nancycollins** [comment]
the array index order was changed in the quad_utils_mod.f90 code when the compiler warned about non-contiguous array access.  but the original order was selected because it is more natural for the models and for the quad utilities.  i believe this change was one of those 'optimize some small routine which doesn't actually affect overall run time, at the expense of doing what seems more natural to the rest of the code'.  i'd support reverting it to the original order, if we could do that without introducing more bugs into the code.

**Comment by hkershaw-brown** [comment]
```
2580 ! Rectangular bilinear interpolation
!>@todo FIXME should this code check invals(:) for MISSING_R8?
!> it costs time and for grids that don't have missing data it is
!> not needed.  should it call allow_missing_in_state() on init and
!> key off that?  (i think yes.)

if (missing_ok_in_state) then

   ! have to do the items individually because some items might
   ! have missing and others not.
   do i=1, nitems
      if (any(invals(:, i) == MISSING_R8)) then
         outvals(i) = MISSING_R8
         istatus(i) = 1
      else
         xbot(1) = invals(1, i) + lon_fract * (invals(2, i) - invals(1, i))
         xtop(1) = invals(4, i) + lon_fract * (invals(3, i) - invals(4, i))
         outvals(i) = xbot(1) + lat_fract * (xtop(1) - xbot(1))
         istatus(i) = 0
      endif
   enddo
   return

else
```

**Comment by hkershaw-brown** [comment]
closing since we've not done anything with this for some time. 
May look at it as part of the quad_util_mod rotations issue #453
