### ISSUE TITLE
Multiple localization radii only supported for threed sphere location

### ISSUE THREAD

**Issue by hkershaw-brown** [NCAR/DART#260]
In assim_tools_mod you can give a list of observation types and a list of cutoffs

&assim_tools_nml :: special_localization_obs_types
&assim_tools_nml :: special_localization_cutoffs

The code to deal with different cutoffs (0.5 *maxdists) is in  threed_sphere/location_mod.f90.  So, only models that use 3D sphere can make use of special localization cutoffs. 

close close obs caching is diasabled in assim_tools_mod when there are different cutoffs since the cuttoff logic is in location_mod.

**Comment by hkershaw-brown** [comment]
There was a user request for how to implement multiple localization for CM1 which uses the threed_cartesian location_mod. 
Is multiple location radii something that should be general and work with any location_mod.

**Comment by jlaucar** [comment]
It would be nice for this to be a general capability. Our other location modules are more commonly used in simple model experiments in which there may not be large numbers of different obs types or in which details of the localization may not have a bit impact on performance, so this was not originally considered when implementing. CM1 has gotten limited use but people could do nice science with it. The oned models could also use this, for instance Ishraque's problem might want to use this. Priority outside of the CM1 user should be considered low since nobody has clamored for this in the last decade.

**Comment by hkershaw-brown** [comment]
see https://github.com/NCAR/DART/pull/285

**Comment by hkershaw-brown** [comment]
closing for now since Jon Labriola provided the capability for the the 3D cartesian location mod.
