### ISSUE TITLE
WOD dataset

### ISSUE THREAD

**Issue by timhoar** [NCAR/DART#31]
Mon, Jun 22, 8:32 PM

I'm a freshman on using the DART. And I want to know where I can find the correponding WOD data, which are used in the DART, after the quality control?

**Comment by johnsonb-ucar** [comment]
Hi Libin,

The original WOD13 data are available here via the NOAA website:

https://www.nodc.noaa.gov/OC5/WOD13/

We provide programs, known as obs_converters, for processing this data into the proprietary obs_seq format that is used for ensemble assimilation with DART. The description of the WOD obs_converter can be found here:

https://github.com/NCAR/DART/blob/Manhattan/observations/obs_converters/WOD/WOD.html

However, I encourage you to read through and understand the DART documentation regarding observation processing:

https://dart.ucar.edu/pages/Observations.html

because the DART quality control flags apply to data that has been used within the context of a specific assimilation. Here is the relevant [set of slides describing these quality control flags](https://dart.ucar.edu/tutorial/section_14.pdf). The overall set of tutorial slides can be found here:

https://dart.ucar.edu/pages/Tutorial.html

Hope this helps,

Ben
