### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by jlaucar** [NCAR/DART#310]
There is an inappropriate check for an outlier when updating posterior inflation with groups in filter_assim. This problem is only possible when running posterior spatially-varying adpative inflation with more than one group. In that case, an outlier threshold is computed with a hard-coded threshold of 3 for each group. However, an outlier threshold with the namelist value has already been computed when the posterior forward operator is computed. A fix for this will simply comment out the current check on an okay value for the outlier_ratio with a statement that is always true. This problem would impact any model. 

            if (inflate_only) then
               diff_sd = sqrt(obs_err_var + r_var)
               if (diff_sd > 0.0_r8) then
                  outlier_ratio = abs(obs(1) - r_mean) / diff_sd
*                 ! Outlier thresholds already enforced by posterior forward operators
*                 !do_adapt_inf_update = (outlier_ratio <= 3.0_r8)
*                 ! Always update the posterior, no matter what the group outlier_ratio
*                 do_adapt_inf_update = .true.
               endif

The proposed fixed code is above. The four lines with a preceding asterisk indicate the change. Obviously, more code could be removed here but I want the footprint to be absolutely minimum.

### Version of DART     
v9.11.12-1-gabff04a93 

### Have you modified the DART code?   
Yes but haven't yet made a pull request.

**Comment by mgharamti** [comment]
Quite a long time ago when I worked on the posterior inflation algorithm this confused me a lot. I think the code is correct in its current form. The only ugly bit is that the outlier threshold is hard-coded (also fixed to 3) and it shouldn't be. The input outlier threshold value (from the namelist) should used here in a more elegant way. Here's why I think we shouldn't comment out this part of the code. 

It's true that we already found the QC values when computing the posterior forward operators but the way we update posterior inflation is quite special. For each observation, we simulate a new independent observation by removing its impact on the posterior mean and variance. Technically, the new 'modified' mean and variance have been impacted by all observations except for the current one. In order to use this new independent observation to update the inflation, we need to check the outlier threshold criteria and make sure it's met.   

Am I making sense? I could be horribly wrong here. Please correct me if I'm mistaken.

**Comment by jlaucar** [comment]
Moha,
Let's talk about this tomorrow. I believe that this extra outlier check
only occurs with more than one group. Jeff
