### ISSUE TITLE
what to do with svn $URL$ $Revision$ $Date$?

### ISSUE THREAD

**Issue by hkershaw-brown** [NCAR/DART#320]
svn info  no longer populated since the code is under git for version control.

```
! version controlled file description for error handling, do not edit
character(len=256), parameter :: source   = "$URL$"
character(len=32 ), parameter :: revision = "$Revision$"
character(len=128), parameter :: revdate  = "$Date$"
```

```
call register_module(source, revision, revdate)
```

```
call error_handler(E_ERR,'model_interpolate',string1, source, revision, revdate)
```

**Comment by nancycollins** [comment]
at one point i made a sed script that would remove source, revision, revdate from any error_handler calls.  if you are interested i can dig it back up. 

otherwise, my opinions:

1. register_module calls should be removed.  i think the subroutine exists and simply returns without printing anything so it doesn't hurt to call it but it also is useless.

2. revision and revdate should be removed.  source could either be removed or could be set to the module name or path to the module. 

3. the additional args to the error_handler should be removed, although source could stay if it's changed to be a fixed name.

if it's too much work to remove the args to the error_handler calls, the quickest fix is to hardcode revision and revdate to empty strings and put the module name in as source.  then the error_handler calls still work without printing garbage.

**Comment by hkershaw-brown** [comment]
closing, not doing anything with this for now.
