### ISSUE TITLE
Bug? approximate_distance = .true./.false.

### ISSUE THREAD

**Issue by hkershaw-brown** [NCAR/DART#346]
Note on approximate_distance = .true. vs. approximate_distance = .false.

approximate_distance = .true. 
one close points, distance = 0.  Can it really be zero?  (un)lucky observation location?
![Screen Shot 2022-04-21 at 9 13 10 AM](https://user-images.githubusercontent.com/20047007/164501696-07074e67-b0da-43b6-9b61-5ebfb9ce1532.png)

approximate_distance = .false.
five close points 
![Screen Shot 2022-04-21 at 9 50 22 AM](https://user-images.githubusercontent.com/20047007/164501783-be3f4c52-e548-483a-b042-1037459241d4.png)

_Originally posted by @hkershaw-brown in https://github.com/NCAR/DART/issues/343#issuecomment-1105413795_

**Comment by hkershaw-brown** [comment]
@Benjamin-Gunn I will have to dig out the test case for this.

**Comment by hkershaw-brown** [comment]
Test case for cam-se on Cheyenne: /glade/scratch/hkershaw/DART/CAM/test-cam-se
Runs on 1 node on Cheyenne

Note a the start of this summer (2022) to use the debugger DDT, you had to compile dart with openmpi.
```
module load openmpi
./quickbuild.sh
```
Script to submit a DDT job is in:
/glade/scratch/hkershaw/DART/CAM/test-cam-se/submit_me-ddt.sh

**Comment by hkershaw-brown** [comment]
Nameslist option is in input.nml

&location_nml
approximate_distance = .false.

**Comment by nancycollins** [comment]
i took a look at this.  here's the issue.

the approximate distance option for localization runs faster because it precomputes a table of sin/cos/acos values and uses them rather than calling trig functions multiple times while computing distances on the sphere.

for localization in global models a slight difference between the approx and exact distance values has a negligible impact on the results.  the distance is used to compute a fraction of the localization function (e.g. gaspari-cohn) and then that factor is folded into the computation of the increments being applied to other locations.

in regional models where the total distances are much smaller we have seen banding in the output field values that results from the approximations, and so we've recommended that approximate_distance = .false. for those cases.  (the suggested input.nml's in the various model directories could be checked to see if this is still true.)

the problem here results from using an approximate get_dist() outside of the localization.  using get_dist() *is* recommended because it is very complex to quickly compute distances on the sphere.   get_dist() is a standard public function and it should be used instead of trying to code up a private function.   here it is used to decide if a point is inside or outside a quad so the accuracy matters.  

in the best of all worlds it would be nice to allow the namelist option for approx vs exact distance to only affect the get_dist() call in the get_close calls for localization, and provide another way to specify this needs to be an exact computation and ignore the precomputed tables if approx dist is true.

it would be interesting to time a large run with and without approximate distance.  if compilers have gotten faster with their intrinsics and the overall run speed isn't significant, an easy solution is to drop support for the approximate distance optimization and always call the trig functions.  i suspect the times will differ, but that's one of those things you can't tell without doing the tests.

if approx distance is still significantly faster, here are some of the issues to consider when designing a solution:
- all location modules must have the same prescribed interfaces so adding new interfaces requires all to be updated
- changing the interface to an existing routine has the same coding overhead
- get_dist() is called a huge number of times during a large run and efficiency here matters a lot
- the size of the precomputed trig tables are set at compile time so they don't have to be allocated at run time.  making them larger makes the approximation more accurate, but for a use case like the one in this bug report there isn't a guarantee how large they might have to be to avoid issues like this.

**Comment by nancycollins** [comment]
p.s. to my last comment.  i don't really understand the algorithm here.  if this code is computing distances over a small enough region that the curvature of the earth doesn't matter, then the distances maybe could be computed another way with simpler code that assumes a flat surface.

**Comment by nancycollins** [comment]
we discussed this briefly in the software standup meeting.  jeff says this is a known issue and that the documentation for CAM-SE should already mention that this model requires setting approx distance false for exactly this reason.  that lowers the priority of doing anything about this issue.

however it would be interesting to time the difference between approx and exact distances over a full run to see if using exact distances everywhere impacts performance vs using approx distances.  if not, there's no need to design a way to use approx in some places and exact in others.   the trick may be to run a CAM-FV case for timing tests if CAM-SE doesn't run the same with and without the approx setting.

**Comment by hkershaw-brown** [comment]
closing for now, for future people, this test case was with the 1deg SE grid: ne30

**Comment by hkershaw-brown** [comment]
Re opening since CAM-SE (CAM 7) is the atm model in CESM3
I don't think this approx distance for cam-se is in the docs (side note, will try finding it with rtd search https://github.com/NCAR/DART/issues/1106)

**Comment by hkershaw-brown** [comment]
The only docs I can find on approximate distance say in general global models use approximate_distance = .true.

https://docs.dart.ucar.edu/en/latest/assimilation_code/location/threed_sphere/location_mod.html#approximate-distances

There is a note in the se model_mod:
https://github.com/NCAR/DART/blob/ab4a62cfdcff107005f6c9b508035c7dfb6d6ca5/models/cam-se/model_mod.f90#L2857-L2877

However the one close points, distance = 0 will not get caught by this check.
