### ISSUE TITLE
twod location_mod is missing required public parameters/routines

### ISSUE THREAD

**Issue by hkershaw-brown** [NCAR/DART#382]
the location_io_mod is expecting the location_mods to have the following routines/parameters.

```
use        location_mod, only : location_type, get_location, &
                                LocationDims, LocationName, LocationLName, &
                                LocationStorageOrder, LocationUnits, &
                                has_vertical_choice, query_location

```

twod location_mod is missing:

```
LocationStorageOrder
LocationUnits
has_vertical_choice
```

Edit: also get_close_obs. get_close_state, convert_vertical_obs, convert_vertical_state

Edit2: test_interpolate_twod.f90 does not compile

**Comment by hkershaw-brown** [comment]
I'm missing why convert_vertical_obs and convert_vertical_state are in the location_mods. 

All the routines look like this: just `istatus = 0`

```
subroutine convert_vertical_state(ens_handle, num, locs, loc_qtys, loc_indx, &
                                  which_vert, istatus)

type(ensemble_type), intent(in)    :: ens_handle
integer,             intent(in)    :: num
type(location_type), intent(inout) :: locs(:)
integer,             intent(in)    :: loc_qtys(:)
integer(i8),         intent(in)    :: loc_indx(:)
integer,             intent(in)    :: which_vert
integer,             intent(out)   :: istatus

istatus = 0

end subroutine convert_vertical_state
````

The location_mods don't know anything about the state or quantities, so they can not be responsible for vertical conversion. 

I propose convert_vertical_obs and convert_vertical_state go in default_model_mod, since they are a do nothing or the model_mod writes its own version of the routines.

**Comment by hkershaw-brown** [comment]
Hot take that I haven't thought through:

* remove the ensemble_handle from the location mods, get_close_state, get_close_obs go in the default model_mod
* get_close in the location mod is just get_close(no ens_handle).

**Comment by nancycollins** [comment]
these are tricky.  if the model_mod wants to use them as a passthrough (e.g. use location_mod : get_close_xxx) then yes, they don't need an ensemble handle.  but if the model_mod wants to implement its own get_close routine, then in many cases it does need an ensemble handle.  i think it's dangerous to have routines with the same names and different calling sequences.  maybe the better solution would have been to have a different name for the routines in the location mods, and have a cover routine in the default_model_mod that calls it for the case where the model_mod doesn't need to write get_close_xxx code.  in that case, with different names, i'd be fine to drop the ensemble handle from the location versions.

**Comment by hkershaw-brown** [comment]
Yeah I like this - defaut_model_mod has the ensemble_handle and has get_close_state/obs , location_mod get_close_state/obs become loc_get_close.

**Comment by nancycollins** [comment]
i suspect changing this will affect most model_mods, but we have done that before.  most of the low order models probably use the pass-through routine (use location_mod : get_close_xx), so they'd have to use it from the default_model_mod instead of the location_mod.  the higher order models mostly have their own code, but many call the location_mod versions to get a default list and then have additional code to modify the list.  they'd have to change the calling sequence that calls the location_mod version to drop the ensemble handle.

pros:  it would drop the dependencies on ensemble_handles in the location mods and simplify them
cons: it requires altering all the model_mods plus publishing instructions on how users need to modify their own code to continue to work.  

it might good to revisit other things in the location_mods (e.g. public constants instead of accessor routines).   if you can come up with a list of 2 or 3 things that could make the interdependence of modules simpler then doing all the changes at once could be worth it.
