### ISSUE TITLE
avoid updating coastal regions in POP

### ISSUE THREAD

**Issue by timhoar** [NCAR/DART#41]
**Ed note: This issue was originally reported 28 Jan 2015 and is being manually ported over to GitHub.**

> ... getting crashes in POP which appear to be made worse by assimilating obs near coastal regions.
> 
> unfortunately in get_close_obs() in the pop model_mod, there is no easy way to tell what the
> corresponding KMT/KMU array is -- we only have access to the location lat/lon/depth and not the column index.
> 
> so she's going to try in the sv_to_restart_file() routine to add code to read back in the original field
> values before doing the update, and for coastal regions keep the original state values instead of
> overwriting them with the assimilated values.

24 Feb 2015
I just touched base and she is not yet happy with her proposed solution because she is still getting some
intermittent crashes in POP in shallow areas. so this is still an open issue.

**Comment by johnsonb-ucar** [comment]
I'm closing this issue because it turns out that Helen -- or perhaps Alicia -- already fixed this. In any case, the commit was made by Helen. The bug was partially caused because the equation for computing KMU was defined incorrectly in the POP reference manual.

She compared the equation in the reference manual against what was actually being done in the source code:
`/glade/p/cesm/releases/cesm1_2_2/models/ocn/pop2/source/grid.F90`
and wrote the `read_topography` subroutine correctly.

To see the commit:
`> cd ${DARTROOT}`
`> git diff f1ca18dee71813af..e8f601ce24a4c70d models/POP/dart_pop_mod.f90`
