### ISSUE TITLE
bug: WRF observations with VERTISUNDEF

### ISSUE THREAD

**Issue by hkershaw-brown** [NCAR/DART#486]
:bug: :ant: Your bug may already be reported!
Please search on the [issue tracker](https://github.com/NCAR/DART/issues) before creating a new issue.

### Describe the bug

User reported using WRF and radiance obs.

1. List the steps someone needs to take to reproduce the bug.  
Run WRF with an observation that has VERTISUNDEF for the vertical location
2. What was the expected outcome?
The distance calculated in get_close should be the horizontal distance whether you have the 
```
&location_nml 
  horiz_dist_only =.true./.false.
```
3. What actually happened?  
The distance calculated changes for the VERTISUNDEF case depending on `horiz_dist_only =.true./.false.`

### Error Message  
No error, incorrect distances

### Which model(s) are you working with?
WRF
User is working with WRF v4

### Screenshots   
![Screen Shot 2023-05-31 at 10 36 10 AM](https://github.com/NCAR/DART/assets/20047007/62050fc8-7b84-4d51-9c37-6557f3d91c3c)

### Version of DART      
Which version of DART are you using? 
v10.7.2-2-ga56916533

### Have you modified the DART code?   
Yes
If your code changes are available on GitHub, please provide the repository.
To reproduce the bug I am using a WRF v4 test case provided by the user. This requires a change to the WRF state (THM vs T in the wrf/model_mod.f90) 
see https://github.com/NCAR/DART/compare/main...lukas-vertundef-wrf

### Build information
Please describe:  
 1. mac laptop 
 2. intel (and gnu for kicks)

## Notes
I'm unclear yet on whether setting `whichvert_obs_in_localization_coord = 0` is a problem. 
https://github.com/NCAR/DART/blob/72e5740b71ef6c7cde4c6f946e2c1df2019365fb/assimilation_code/modules/assimilation/assim_tools_mod.f90#L592-L593

0 is undefined as a vertical localization coord for the 3d sphere lcoation_mod:
https://github.com/NCAR/DART/blob/72e5740b71ef6c7cde4c6f946e2c1df2019365fb/assimilation_code/location/threed_sphere/location_mod.f90#L59-L67

**Comment by hkershaw-brown** [comment]
notes from dart support email back and forth on the get_close call causing the error:

In wrf model_mod.f90 if you change line 6424 to  dist(k) = 1.123e9 you can see that it is this line that is setting the large value (rather than it just being the initialization of dist). For the undefined vertical `local_array(3) == missing_r8` so you get 1.123e9 for  horizontal_distance_only = .false.

```diff
6419       if (present(dist)) then
6420          ! Compute distance - set distance to a very large value if vert coordinate is missing
6421          ! or vert_convert returned error (istatus2=1)
6422          local_array = get_location(local_loc)
6423          if (((vertical_localization_on()).and.(local_array(3) == missing_r8)).or.(istatus2 == 1)) then
- 6424             dist(k) = 1.123e9
6425          else
6426             dist(k) = get_dist(base_loc, local_loc, base_type, loc_qtys(t_ind))
6427          endif
6428       endif
```

There is a fix on https://github.com/NCAR/DART/tree/lukas-vertundef-wrf
https://github.com/NCAR/DART/blob/a5691653380128246853c4a5dc18176ecdb56709/models/wrf/model_mod.f90#L6406-L6411

I'm not sure whether missing_r8 can occur in wrf for verticals other than VERTISUNDEF
  > if (((vertical_localization_on()).and.(**local_array(3) == missing_r8**)).or.(istatus2 == 1)) then  

so I left the **local_array(3) == missing_r8** in and put an earlier check for VERTISUNDEF.

**Comment by lkugler** [comment]
Hi Helen,
Thank you very much for your proposed solution (https://github.com/NCAR/DART/tree/lukas-vertundef-wrf).
I tested it in this configuration: [input.nml.txt](https://github.com/NCAR/DART/files/11707602/input.nml.txt) , 5776 observations of infrared 6.2 µm brightness temperature [Kelvin]; one observation every 4 km with a horizontal localization half-width of 25 km.



The result for the RMSE in K
1)  `horiz_dist_only =.true.` and old code
```
prior RMSE [K]:  2.623838357303896
posterior RMSE [K]:  1.5235920807597159
```

2)  `horiz_dist_only =.false.` using the old code (BUG)
```
prior RMSE [K]:  2.623838357303896
posterior RMSE [K]:  2.7572305021473866
```

3)  `horiz_dist_only =.false.` using your proposed solution (FIX)
```
prior RMSE [K]:  2.623838357303896
posterior RMSE [K]:  1.5235920807597159
```
=> The proposed solution fixes the reported bug. 

### Code changes
So to summarize, the `get_close` routine in [model_mod.f90](https://github.com/NCAR/DART/blob/a5691653380128246853c4a5dc18176ecdb56709/models/wrf/model_mod.f90#L6400) first calculates 2D-distance if  VERTISUNDEF, if not it converts the vertical coordinate in order to calculate the 3D-distance, and if the vertical coordinate is -88888 even though it has a valid vertical coordinate, then it uses 1e9 as distance, rather than to fail or give an error message.

Probably a minor thing: Why did you change this "large distance" from 1.0e9 to 1.123e9?

### Relevant to other models?
I also tried to understand how this works for CESM/CAM-FV/CAM-SE [model_mod.f90](https://github.com/NCAR/DART/blob/lukas-vertundef-wrf/models/cam-fv/model_mod.f90#L2254) but I'm not sure. Maybe this could be checked, since it could have a large impact. Is it necessary for `get_close_obs()` to be different for these models?


### Relevance
- I expect that this fix will be crucial for getting beneficial impact from high-resolution, "dense" observations or also other cases, when the distance between observations is smaller than the localization radius and there is a high covariance between the priors of two spatially-close observations. 
- This fix does not affect results of previous studies using `horiz_dist_only=.true.`.
- But when horiz_dist_only=.false. and there are observations with undefined vertical location, this fix would likely have improved the results.

**Comment by hkershaw-brown** [comment]
> Probably a minor thing: Why did you change this "large distance" from 1.0e9 to 1.123e9?

This was so I could differentiate between these two cases:  dist gets initialized to 1.0e9 and never changed:
https://github.com/NCAR/DART/blob/502af7865e258530cba7c7daff6aed4390cbb649/models/wrf/model_mod.f90#L6370

and the value dist gets set to for a 'failing' vertical conversion: (I just needed this to be big and not 1.0e9)
https://github.com/NCAR/DART/blob/502af7865e258530cba7c7daff6aed4390cbb649/models/wrf/model_mod.f90#L6423-L6425

**Comment by hkershaw-brown** [comment]
> I also tried to understand how this works for CESM/CAM-FV/CAM-SE [model_mod.f90](https://github.com/NCAR/DART/blob/lukas-vertundef-wrf/models/cam-fv/model_mod.f90#L2254) but I'm not sure. Maybe this could be checked, since it could have a large impact. Is it necessary for get_close_obs() to be different for these models?

The vertical coordinate, and vertical localization are model specific.  For example, CAM damps the impact of observations at the top of the model. 
But I would say your instinct is correct, these two get_close_obs routines do not have to be as different as they are.
