### ISSUE TITLE
DOI to point to repo

### ISSUE THREAD

**Issue by hkershaw-brown** [NCAR/DART#699]
The citation for DART currently points to the website

Discussion 7/10/2024 concluded that the DOI should point to the repo. 

contacted ucar library about doi.

**Comment by nancycollins** [comment]
trivia:  i think the original DOI went to the website because at that time people needed to fill out a form on the website with contact info and what they intended to do with dart. we logged that for our user stats. then they got redirected to the svn repository location for the code. now with github the DOI can go directly to the repo.

**Comment by hkershaw-brown** [comment]
doi now points to repo.
